name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -v ./...

      - name: Format
        run: diff <(gofmt -d .) <(echo -n)
