# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Codewise-CLI
      run: go install github.com/aryansharma9917/Codewise-CLI@latest

    - name: Add Go bin to PATH
      run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Test
      run: go test -v ./...
